#make solo ejecuta la primera linea, asi que esa es la ultima que debe ejecutarse, la que implica las otras dependencias, de alguna forma
#como all nunca se crea, siempre lo hace y revisa las dependencias para ambos lineas_x.txt
#como clean no esta en la primera linea solo lo hace si se llama make -f makefile.2 clean

all : lineas_1.txt lineas_2.txt  

lineas_1.txt : numeros.txt lineas.py
	python lineas.py
	
lineas_2.txt : numeros.txt lineas.py
	python lineas.py

numeros.x : numeros.c
	gcc numeros.c -o numeros.x
	
numeros.txt : numeros.x
	./numeros.x > numeros.txt
	
clean:
	rm -f numeros.x lineas_*.txt numeros.txt
